### ISSUE TITLE
Build with new 4.24 project fails: wrong BuildSettingsVersion or incomplete include paths

### ISSUE THREAD

**Issue by RogueSheep-nl** [feixuwu/UEWebsocket#76]
Using the plugin in a new 4.24 project, the build fails.

Some fixes have been presented in this thread: #73 

You also need to make sure to check _BuildSettingsVersion_  in the [project_name](Editor).Target.cs)

When using V2 (as is default in new 4.24 projects), your build will fail on these includes in _Plugins/WebSocket/Source/WebSocket/Private/WebSocketContext.cpp_:
```
#include "UObjectGlobals.h"
...
#include "Paths.h"
#include "FileManager.h"
#include "FileHelper.h"
```

First error will be:
> Plugins/WebSocket/Source/WebSocket/Private/WebSocketContext.cpp(25): fatal error C1083: Cannot open include file: 'UObjectGlobals.h': No such file or directory

2 possible solutions here:
1. Set _BuildSettingsVersion_  to _V1_
2. Use full paths:
```
#include "UObject/UObjectGlobals.h"
...
#include "Misc/Paths.h"
#include "HAL/FileManager.h"
#include "Misc/FileHelper.h"
```
Please note: This did get the solution build, I have not been able to perform a proper functional test yet.

**Comment by irajsb** [comment]
agreed . just removing ` "DefaultBuildSettings = BuildSettingsVersion.V2;`" from target files worked for me but its possible in feature v1 be not available so  using full path names is a better option . also @feixuwu pls add this to readme because plugin is not usable without this.

**Comment by feixuwu** [comment]
I submit a new commit fixed all the package error and warning.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: iraj mohtasham <notifications@github.com>
发送时间: Thursday, March 19, 2020 11:42:13 PM
收件人: feixuwu/UEWebsocket <UEWebsocket@noreply.github.com>
抄送: xufeiwu <feixuwu@outlook.com>; Mention <mention@noreply.github.com>
主题: Re: [feixuwu/UEWebsocket] Build with new 4.24 project fails: wrong BuildSettingsVersion or incomplete include paths (#76)


agreed . just removing "DefaultBuildSettings = BuildSettingsVersion.V2;" from target files worked for me but its possible in feature v1 be not available so using full path names is a better option . also @feixuwu<https://github.com/feixuwu> pls add this to readme because plugin is not usable without this.

―
